---
# https://github.com/bitnami/charts/tree/main/bitnami/contour

envoy:
  kind: deployment
  service:
    type: ClusterIP
    clusterIP: None
    externalTrafficPolicy: ""
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "controller"
      effect: "NoSchedule" 
  nodeSelector:
    dedicated: controller
  containerSecurityContext:
    runAsUser: 0
    runAsNonRoot: false
